server {
    listen 80;
    listen 443 ssl;
    server_name prod.sigmasoftinfotech.com;

    ssl_certificate     /etc/ssl/certs/sigmasoftinfotech_fullchain.crt;
    ssl_certificate_key /etc/ssl/private/sigmasoftinfotech.key;

    location /connectado_outlook/ {
        alias /usr/share/nginx/html/connectado_outlook/;
        index taskpane.html;
        try_files $uri $uri/ /connectado_outlook/taskpane.html;
    }

    # Optional: Redirect root to the app
    location / {
        return 301 /connectado_outlook/taskpane.html;
    }
}
